import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <br />
          <a href="/">Home</a> / &nbsp;
          <a href="/login">Login</a>  
          <br />
          <Link href="/">Home</Link> / &nbsp;
          <Link href="/login">Login</Link>  
          <br />
          <br />
        </div>
            {children}
        </body>
        </html>
    )
}

/*
a 태그 vs Link 컴포넌트 (예: Next.js Link)
페이지 전환 방식

a 태그: 브라우저가 전체 페이지를 새로 요청/새로고침해서 이동 (전통적인 방식).
Link 컴포넌트: 클라이언트 사이드 라우팅으로 이동 → 필요한 데이터만 가져오고, 레이아웃은 유지되어 더 빠르고 부드러운 전환.
앱 상태 유지

a 태그: 새로고침되면서 리액트 상태, 전역 상태 등이 초기화됨.
Link 컴포넌트: SPA 방식이라 상태를 최대한 유지하면서 페이지 이동.
추가 기능 (프리패치 등)

a 태그: 단순 링크, 추가 최적화 없음.
Link 컴포넌트: 스크롤에 보이거나 가까워질 때 미리 다음 페이지 데이터/코드를 프리패치해서 체감 속도 향상.
사용 위치

내부 라우트 이동: Next.js / React Router 등에서는 Link를 사용하는 것이 권장.
외부 사이트 이동, 파일 다운로드, mailto 등: 보통 그냥 a 태그 사용.
*/